"""remove category from expenses

Revision ID: 0da2194dfa7f
Revises: f1f90157fafb
Create Date: 2026-02-23 09:01:21.838893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da2194dfa7f'
down_revision = 'f1f90157fafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), server_default=sa.text("'General'::character varying"), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
