"""sync_check

Revision ID: 1b07e4373e88
Revises: 6073798869bc
Create Date: 2026-02-13 09:46:09.638159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b07e4373e88'
down_revision = '6073798869bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('split_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('version')
        batch_op.drop_column('split_type')

    # ### end Alembic commands ###
