"""add audit columns

Revision ID: a2b2c2d2e2f2
Revises: f1f90157fafb
Create Date: 2026-02-23 09:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b2c2d2e2f2'
down_revision = 'f1f90157fafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_edited_by', sa.Integer(), sa.ForeignKey('expense_users.id'), nullable=True))
        batch_op.add_column(sa.Column('last_edited_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('last_edited_at')
        batch_op.drop_column('last_edited_by')

    # ### end Alembic commands ###
